Sport vs Politics

In [14]:
import tweepy
import pandas as pd
import numpy as np
import re

In [15]:
consumer_key = ""
consumer_secret = ""
access_token = ""
access_secret = ""
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
api = tweepy.API(auth)


In [16]:
version = api.get_place_trends(721943)

In [17]:
keywordsPolitics = "Meloni OR Letta -filter:retweets"

In [18]:
keywordsSport = "Ronaldo OR NBA -filter:retweets"

myGetTweets(keywords, numberOfTweets) is a function that given a text string (keywords) gets the following information for a number of tweets:
-creation date;
-place where it was tweeted;
-username of the creator;
-text of the tweet.

Note: it doesn't get retweets.

In [19]:
def myGetTweets(keywords, numberOfTweets):
    object1 = tweepy.Cursor(api.search_tweets, q = keywords + " -filter:retweets", lang = "it").items(numberOfTweets)
    return [[tweet.created_at, tweet.place, tweet.user.name, tweet.text] for tweet in object1]

In [20]:
display(myGetTweets(keywordsSport, 100))

[[datetime.datetime(2022, 11, 25, 10, 48, 2, tzinfo=datetime.timezone.utc),
  None,
  'Real Madrid - Afrique',
  'Cristiano Ronaldo.. hahaha🤩🤩🤩 https://t.co/rcZ0CodtfZ'],
 [datetime.datetime(2022, 11, 25, 10, 46, 54, tzinfo=datetime.timezone.utc),
  None,
  'Paolo Fornasari 🇪🇺🇮🇹 🇺🇦',
  "Banchero parla già da italiano: 'Siamo forti' https://t.co/dHFViaAHXG via @SkySport #NBA #NBATipo #NBA2K23 @parallelecinico"],
 [datetime.datetime(2022, 11, 25, 10, 46, 1, tzinfo=datetime.timezone.utc),
  None,
  'Calciomercatoweb.it',
  "Il #ManchesterUnited ha trovato l'erede di #CristianoRonaldo: è Marcus #Thuram 🇫🇷 , già nel mirino 🎯 dell'#Inter \n\nhttps://t.co/3ZmT0qwuZz"],
 [datetime.datetime(2022, 11, 25, 10, 43, 30, tzinfo=datetime.timezone.utc),
  None,
  'dom_zine',
  '@Corso_DJ @muaniano @Ceruzeko @wazzaCN No Bro, Ronaldo al Milan al massimo ha vinto una coppa da Ancelotti. Il salu… https://t.co/4wESlpC57T'],
 [datetime.datetime(2022, 11, 25, 10, 43, 3, tzinfo=datetime.timezone.utc),
  None,

In [21]:
def myGetOnlyTweets(keywords, numberOfTweets):
    object1 = tweepy.Cursor(api.search_tweets, q = keywords + " -filter:retweets", lang = "it").items(numberOfTweets)
    object2 = [[tweet.text] for tweet in object1]
    return pd.DataFrame(object2)

In [22]:
display(myGetOnlyTweets(keywordsSport, 100))

0
0   Cristiano Ronaldo.. hahaha🤩🤩🤩 https://t.co/rcZ...
1   Banchero parla già da italiano: 'Siamo forti' ...
2   Il #ManchesterUnited ha trovato l'erede di #Cr...
3   @Corso_DJ @muaniano @Ceruzeko @wazzaCN No Bro,...
4   @callmekimjongun @lamborghinat Ronaldo bruno joao
..                                                ...
95  Le parole del ministro dello sport dell'#Arabi...
96  @thisisoslooo xvideos una typical Ronaldo dixx...
97  Gol in 5 mondiali differenti. Non sarà quello ...
98  Cristiano Ronaldo, un club fa retromarcia: le ...
99  Leao esaltato dalla stampa: più decisivo di CR...

[100 rows x 1 columns]

In [23]:
sportDataSet = myGetOnlyTweets(keywordsSport, 100)

In [24]:
dfLabels = ["sport" for i in range(100)]

In [25]:
sportDataSet['class'] = dfLabels

In [26]:
display(sportDataSet)

0  class
0   Cristiano Ronaldo.. hahaha🤩🤩🤩 https://t.co/rcZ...  sport
1   Banchero parla già da italiano: 'Siamo forti' ...  sport
2   Il #ManchesterUnited ha trovato l'erede di #Cr...  sport
3   @Corso_DJ @muaniano @Ceruzeko @wazzaCN No Bro,...  sport
4   @callmekimjongun @lamborghinat Ronaldo bruno joao  sport
..                                                ...    ...
95  Le parole del ministro dello sport dell'#Arabi...  sport
96  @thisisoslooo xvideos una typical Ronaldo dixx...  sport
97  Gol in 5 mondiali differenti. Non sarà quello ...  sport
98  Cristiano Ronaldo, un club fa retromarcia: le ...  sport
99  Leao esaltato dalla stampa: più decisivo di CR...  sport

[100 rows x 2 columns]

In [27]:
politicsDataSet = myGetOnlyTweets(keywordsPolitics, 100)

In [28]:
dfLabels = ["politics" for i in range(100)]

In [29]:
politicsDataSet['class'] = dfLabels

In [30]:
display(politicsDataSet)

0     class
0   Agenzia_Ansa "Alle 11 Varese darà l'ultimo sal...  politics
1   @nicolatosti1 in un certo senso no. Io scherzo...  politics
2   Giornalai, Meloni non vuole smantellare nulla,...  politics
3   La Germania approva il suo nuovo reddito di ci...  politics
4   Io consiglierei al Presidente Meloni di toglie...  politics
..                                                ...       ...
95  L’Ucraina ha bisogno di generatori di corrente...  politics
96  SORPRESA...\nLa bozza del disegno legge di bil...  politics
97  Temo che sia il nostro futuro con questo gover...  politics
98  @valy_s Gli adoratori del Vuoto, delle Griffe,...  politics
99  Caro governo #meloni non e che accendete le lu...  politics

[100 rows x 2 columns]

In [31]:
unclassifiedDataSet = myGetOnlyTweets("", 100)

dfLabels = ["unclassified" for i in range(100)]

unclassifiedDataSet['class'] = dfLabels

display(unclassifiedDataSet)

0         class
0   @marioadinolfi Poi ti chiedi perché ti reputan...  unclassified
1   Il Black Friday arriva al Molo 8.44: ecco le p...  unclassified
2   @mandalacakes Famiglia &gt;&gt;&gt;&gt;&gt;&gt...  unclassified
3   Diretta Olanda-Ecuador ore 17: probabili forma...  unclassified
4   Paulette #棋牌 Fabian #世界杯 Kendall #足球  https://...  unclassified
..                                                ...           ...
95  Più libri più liberi più femminismi più murgis...  unclassified
96  "La presa di Saragozza (marzo 1809)" produzion...  unclassified
97  Jessie Adela #南京 Bruce Theresa #成都 Xanthe Nell...  unclassified
98  La violenza si combatte con l’educazione, l’as...  unclassified
99  Tecnologia additiva: a Udine il primo dicembre...  unclassified

[100 rows x 2 columns]

In [32]:
display(pd.concat([sportDataSet, politicsDataSet, unclassifiedDataSet]))

0         class
0   Cristiano Ronaldo.. hahaha🤩🤩🤩 https://t.co/rcZ...         sport
1   Banchero parla già da italiano: 'Siamo forti' ...         sport
2   Il #ManchesterUnited ha trovato l'erede di #Cr...         sport
3   @Corso_DJ @muaniano @Ceruzeko @wazzaCN No Bro,...         sport
4   @callmekimjongun @lamborghinat Ronaldo bruno joao         sport
..                                                ...           ...
95  Più libri più liberi più femminismi più murgis...  unclassified
96  "La presa di Saragozza (marzo 1809)" produzion...  unclassified
97  Jessie Adela #南京 Bruce Theresa #成都 Xanthe Nell...  unclassified
98  La violenza si combatte con l’educazione, l’as...  unclassified
99  Tecnologia additiva: a Udine il primo dicembre...  unclassified

[300 rows x 2 columns]

In [64]:
initialDataSet = pd.concat([sportDataSet, politicsDataSet, unclassifiedDataSet])

In [34]:
import sklearn as sk

In [35]:
from sklearn import *

In [36]:
myForest = ensemble.RandomForestClassifier()

In [37]:
type(myForest)

sklearn.ensemble._forest.RandomForestClassifier

In [38]:
myForest.fit(initialDataSet[0], initialDataSet['class'])

ValueError: could not convert string to float: 'Cristiano Ronaldo.. hahaha🤩🤩🤩 https://t.co/rcZ0CodtfZ'

In [ ]:
size(initialDataSet[0])


NameError: name 'size' is not defined

In [ ]:
initialDataSet['class']

0            sport
1            sport
2            sport
3            sport
4            sport
          ...     
95    unclassified
96    unclassified
97    unclassified
98    unclassified
99    unclassified
Name: class, Length: 300, dtype: object

In [41]:
initialDataSet[0]

0     Cristiano Ronaldo.. hahaha🤩🤩🤩 https://t.co/rcZ...
1     Banchero parla già da italiano: 'Siamo forti' ...
2     Il #ManchesterUnited ha trovato l'erede di #Cr...
3     @Corso_DJ @muaniano @Ceruzeko @wazzaCN No Bro,...
4     @callmekimjongun @lamborghinat Ronaldo bruno joao
                            ...                        
95    Più libri più liberi più femminismi più murgis...
96    "La presa di Saragozza (marzo 1809)" produzion...
97    Jessie Adela #南京 Bruce Theresa #成都 Xanthe Nell...
98    La violenza si combatte con l’educazione, l’as...
99    Tecnologia additiva: a Udine il primo dicembre...
Name: 0, Length: 300, dtype: object

In [ ]:
import re

In [42]:
display(initialDataSet[0])

0     Cristiano Ronaldo.. hahaha🤩🤩🤩 https://t.co/rcZ...
1     Banchero parla già da italiano: 'Siamo forti' ...
2     Il #ManchesterUnited ha trovato l'erede di #Cr...
3     @Corso_DJ @muaniano @Ceruzeko @wazzaCN No Bro,...
4     @callmekimjongun @lamborghinat Ronaldo bruno joao
                            ...                        
95    Più libri più liberi più femminismi più murgis...
96    "La presa di Saragozza (marzo 1809)" produzion...
97    Jessie Adela #南京 Bruce Theresa #成都 Xanthe Nell...
98    La violenza si combatte con l’educazione, l’as...
99    Tecnologia additiva: a Udine il primo dicembre...
Name: 0, Length: 300, dtype: object

In [43]:
vectorizer = feature_extraction.text.CountVectorizer()


In [45]:
myVectorization = vectorizer.fit(initialDataSet[0])

In [47]:
myVectorization2 = vectorizer.transform(initialDataSet[0])
 
# Summarizing the Encoded Texts
print("Encoded Document is:")
print(myVectorization2.toarray())


Encoded Document is:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [48]:
myForest.fit(myVectorization2, initialDataSet['class'])

RandomForestClassifier()

In [ ]:
apply(X)
Apply trees in the forest to X, return leaf indices.
decision_path(X)
Return the decision path in the forest.
fit(X, y[, sample_weight])
Build a forest of trees from the training set (X, y).
get_params([deep])
Get parameters for this estimator.
predict(X)
Predict class for X.
predict_log_proba(X)
Predict class log-probabilities for X.
predict_proba(X)
Predict class probabilities for X.
score(X, y[, sample_weight])
Return the mean accuracy on the given test data and labels.
set_params(**params)
Set the parameters of this estimator.

In [49]:
myForest.apply(myVectorization2)

array([[139, 179, 224, ..., 109, 136, 166],
       [132, 191, 222, ...,  75, 188, 139],
       [244, 206, 190, ...,  38, 109,  76],
       ...,
       [219, 163, 170, ...,  39,  93,  82],
       [232, 170, 164, ...,  37, 104,  87],
       [232, 170, 153, ...,  37,  91,  76]])

In [50]:
myForest.decision_path(myVectorization2)

(<300x20628 sparse matrix of type '<class 'numpy.int64'>'
 	with 910428 stored elements in Compressed Sparse Row format>,
 array([    0,   265,   496,   721,   872,   993,  1110,  1343,  1528,
         1775,  1968,  2175,  2358,  2657,  2846,  3035,  3170,  3309,
         3518,  3741,  3902,  4181,  4416,  4619,  4864,  5143,  5322,
         5495,  5754,  5989,  6164,  6369,  6548,  6731,  6938,  7227,
         7504,  7709,  7930,  8091,  8284,  8489,  8646,  8863,  9074,
         9231,  9446,  9655,  9842, 10075, 10316, 10487, 10688, 10939,
        11196, 11327, 11496, 11671, 11926, 12051, 12234, 12455, 12678,
        12925, 13160, 13395, 13622, 13779, 13980, 14153, 14266, 14461,
        14686, 14879, 15114, 15339, 15580, 15815, 16092, 16235, 16456,
        16627, 16878, 17133, 17308, 17537, 17782, 17969, 18156, 18409,
        18634, 18889, 19090, 19279, 19458, 19683, 19956, 20161, 20272,
        20461, 20628]))

In [52]:
myForest.get_params(10)

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

Creating a test dataset

In [56]:
testPolitics100 = myGetOnlyTweets("Berlusconi OR Salvini", 100)

In [61]:
dfLabels = ["politics" for i in range(100)]

testPolitics100['class'] = dfLabels

display(testPolitics100)

0     class
0   @salvini_giacomo @Caffe_Graziella e che non lo...  politics
1   @fattoquotidiano @salvini_giacomo meno si va i...  politics
2   Silvio Berlusconi, in arrivo un musical su di ...  politics
3   TV &gt; Rete 4 | Susanna Ceccardi, Europarlame...  politics
4   Calenda la Meloni detto terra terra si para il...  politics
..                                                ...       ...
95  Il crollo nei sondaggi sancisce il fallimento ...  politics
96  @dottorbarbieri @LouisVuitton Questo sta polve...  politics
97  @Monna_Prof Peggior presidente del consiglio d...  politics
98  @Holikachuk @ocaignorante @salvini_giacomo E c...  politics
99  @Holikachuk @ocaignorante @salvini_giacomo C'è...  politics

[100 rows x 2 columns]

In [57]:
testSport100 = myGetOnlyTweets("Qatar22 OR Qatar 20222 OR Qatar OR Fifa OR FIFA", 100)

In [60]:
dfLabels = ["sport" for i in range(100)]

testSport100['class'] = dfLabels

display(testSport100)

0  class
0   Galles - Iran\nQatar - Senegal\nOlanda - Equad...  sport
1   Il Pallone Racconta – Il Brasile si è presenta...  sport
2   Qatar 2022, da Maradona a Richarlison, i più b...  sport
3   Il Pallone Racconta - Il Brasile si è presenta...  sport
4   #Qatar 2022, ILGA scrive alla FIFA: "Sì all'ug...  sport
..                                                ...    ...
95  Buongiorno Mondiale\n\nLe partite di oggi [Rai...  sport
96  Danilo e Alex Sandro trascinano il Brasile: i ...  sport
97  @schickposting Almeno sai dove si trova il Qatar?  sport
98  Indossava una maglia per i diritti delle donne...  sport
99  Oggi faccio il @iosonofreeo della situazione \...  sport

[100 rows x 2 columns]

In [58]:
testUnclassified100 = myGetOnlyTweets("", 100)

In [59]:
dfLabels = ["unclassified" for i in range(100)]

testUnclassified100['class'] = dfLabels

display(testUnclassified100)

0         class
0   @gloquenzi @dorinileonardo Penso che l’incenti...  unclassified
1   Per il "venerdì nero", il Primato propone una ...  unclassified
2   Chester Walpole #世界杯买球 #开云体育 #世界杯 Elsa Stone O...  unclassified
3   @matiasgarciard Madeleinelorenzogarabito@gmail...  unclassified
4   @BdiBeppe @euright9 dai, facciamolo con la pat...  unclassified
..                                                ...           ...
95  @theslvm Chissà perché latitano, eppure essend...  unclassified
96  Gli chiedono di un "compromesso", lui capisce ...  unclassified
97  @CollotMarta Una scuola umiliante non è istrut...  unclassified
98  #Teatro #Verdi #Terni, check stato degli #immo...  unclassified
99  "Il mondo sarebbe un posto di merda senza le d...  unclassified

[100 rows x 2 columns]

In [63]:
testingDataSet = pd.concat([testSport100, testPolitics100, testUnclassified100])

In [65]:
testVectorization = vectorizer.transform(testingDataSet[0])
 
# Summarizing the Encoded Texts
print("Encoded Document is:")
print(testVectorization.toarray())


Encoded Document is:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [69]:
myForest.predict(testVectorization)

array(['unclassified', 'unclassified', 'unclassified', 'unclassified',
       'unclassified', 'unclassified', 'unclassified', 'unclassified',
       'unclassified', 'unclassified', 'unclassified', 'unclassified',
       'unclassified', 'unclassified', 'politics', 'unclassified',
       'unclassified', 'unclassified', 'unclassified', 'unclassified',
       'unclassified', 'politics', 'unclassified', 'unclassified',
       'unclassified', 'unclassified', 'unclassified', 'unclassified',
       'politics', 'unclassified', 'unclassified', 'unclassified',
       'unclassified', 'unclassified', 'politics', 'unclassified',
       'unclassified', 'unclassified', 'unclassified', 'unclassified',
       'unclassified', 'unclassified', 'unclassified', 'unclassified',
       'unclassified', 'unclassified', 'unclassified', 'unclassified',
       'unclassified', 'unclassified', 'unclassified', 'unclassified',
       'unclassified', 'unclassified', 'unclassified', 'unclassified',
       'politics', 'un

In [70]:
myForest.score(testVectorization, testingDataSet['class'])

0.4033333333333333